[
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc pharetra quis dui nec rutrum. Ut eleifend lorem nisl, sed ultrices dolor dapibus vitae. Vestibulum quis lectus sollicitudin, gravida justo eu, adipiscing dolor. Sed posuere nunc eu nibh venenatis accumsan. Aliquam pellentesque mattis faucibus. Quisque sed neque justo. Integer luctus faucibus arcu, tincidunt mollis nunc viverra non. Suspendisse egestas lacinia eros, ac ultrices ante placerat ac. Etiam consequat tincidunt nulla in blandit. Proin pellentesque varius est, et rutrum nisl convallis eu. Nam condimentum turpis aliquet sapien venenatis, vel iaculis dui blandit. Vestibulum iaculis pellentesque ante id malesuada. Suspendisse mollis cursus sodales. Sed viverra pulvinar lacus, a lacinia ipsum sagittis eget. Aenean eu lectus ac tortor adipiscing blandit.",
  "Nam leo metus, blandit tempor lacinia eget, egestas ac magna. Sed aliquam sit amet nulla ac aliquam. Cras eu adipiscing arcu, dignissim feugiat elit. Nulla facilisi. Pellentesque ullamcorper vestibulum porttitor. Donec at blandit nisl. Suspendisse eget enim tempus, congue purus ut, tristique felis. Donec condimentum vitae lacus ac eleifend. Aenean ultrices risus ac tortor suscipit dignissim.",
  "Praesent semper purus at lacus scelerisque, a sagittis odio lacinia. Sed ultrices velit eu sapien tincidunt, a convallis nisi tincidunt. Praesent faucibus augue nec erat volutpat pellentesque. Praesent rutrum nunc nec arcu semper, a lobortis eros sodales. Duis varius, lectus a ornare lobortis, ligula nisi gravida diam, a lobortis magna nunc a elit. Nullam fringilla, justo a feugiat consectetur, magna enim semper metus, eu adipiscing mauris mauris vel eros. Nulla placerat lobortis dui sed porta. Quisque feugiat mauris vel fringilla imperdiet.",
  "Praesent euismod in tellus quis feugiat. Vivamus sit amet molestie turpis, in vehicula tellus. Integer id ligula enim. Vestibulum est lorem, malesuada et tempus ut, condimentum vel ligula. Proin tempus, diam vestibulum laoreet hendrerit, tortor massa rhoncus neque, vel auctor ante dolor id urna. Praesent tellus neque, vestibulum quis suscipit et, cursus at felis. Curabitur tincidunt dui a tempus congue. Phasellus a iaculis neque. Nam tincidunt massa non faucibus viverra.",
  "In massa risus, fermentum eget elit sit amet, condimentum placerat enim. In hac habitasse platea dictumst. Integer feugiat lobortis pharetra. Phasellus lacus augue, hendrerit a egestas in, tristique et turpis. Nullam a lorem et risus porttitor ullamcorper. Integer placerat sem lorem, sed ornare arcu laoreet lobortis. Praesent imperdiet tincidunt odio et pharetra. Sed ut diam neque. Pellentesque at cursus erat. Sed in gravida ante, sed suscipit metus. Aenean eu elit erat. Nunc venenatis aliquet scelerisque. Praesent eu odio quis est faucibus fermentum.",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nec aliquet ante. Etiam feugiat nulla erat, at euismod mauris pharetra ut. Sed accumsan leo quis neque posuere porttitor. Sed accumsan at massa nec lobortis. Praesent tincidunt, mi non iaculis commodo, justo velit cursus massa, et congue magna mauris nec magna. Fusce dignissim turpis in dolor cursus blandit et condimentum neque. Ut lobortis adipiscing odio eget ullamcorper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris mi leo, fringilla vel ornare ut, varius vitae augue. Nullam eu feugiat felis, nec laoreet quam. Nullam non dolor tempor, iaculis ipsum ut, viverra purus. Pellentesque lectus leo, congue eu nisl at, aliquet placerat justo. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
  "Ut aliquet enim eu sagittis tempus. Donec ac hendrerit neque. Integer sollicitudin gravida iaculis. Vestibulum a facilisis libero. Aliquam a orci neque. Aenean id orci in justo fringilla vulputate in sit amet justo. Proin nulla orci, dapibus mollis dolor dignissim, auctor imperdiet nibh. Vestibulum lacinia neque a neque commodo luctus. Cras a enim vel tellus porta sagittis nec ac augue. Donec pellentesque, eros quis vestibulum iaculis, turpis erat egestas metus, vel placerat elit augue in augue.",
  "Maecenas convallis, ante et dapibus vehicula, justo tellus mollis lectus, ut varius quam lacus eget tortor. Ut scelerisque felis a blandit interdum. Praesent ut augue vel nisl venenatis ornare quis non diam. Fusce fringilla massa quis adipiscing dapibus. Aliquam malesuada nunc ut eros facilisis accumsan. Morbi sollicitudin, tellus vel dapibus ultrices, ipsum massa laoreet massa, in interdum enim dui quis mauris. Aenean et orci vel libero tempus auctor. Vivamus lacinia sollicitudin neque, quis ullamcorper ipsum tincidunt eget.",
  "In congue sit amet nisl a fermentum. Morbi ligula magna, iaculis ac convallis non, consectetur eu nisi. Donec leo lacus, bibendum in libero nec, vulputate eleifend lacus. Aenean venenatis dolor id lectus consequat tempor. Nunc tortor ligula, congue sed augue id, accumsan imperdiet risus. Quisque non turpis quis nisi mattis lobortis. Ut condimentum tellus ut enim aliquam, vitae pulvinar nibh suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In semper dui ut orci tincidunt, ut eleifend mi tempor. Suspendisse eu est laoreet, convallis diam et, porttitor risus",
  "Duis quis mauris nulla. Nullam vel est quam. Ut mattis tortor ac nulla dignissim, quis cursus velit tincidunt. In sit amet erat massa. Etiam eros est, aliquam non dictum ac, pharetra eget diam. Proin cursus lectus nec sem iaculis, vitae tincidunt mauris sollicitudin. Praesent eget varius orci. Quisque vestibulum dignissim augue. Sed gravida ante a aliquam luctus. Donec tincidunt libero ut urna commodo, eget placerat sem laoreet. In faucibus consectetur odio, vitae elementum orci vulputate vitae. Donec varius nulla nisi, vitae semper velit condimentum id. Suspendisse et neque ut enim ultrices egestas.",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur non odio mi. Fusce consequat fermentum sem, eget vulputate massa imperdiet sit amet. Quisque rutrum malesuada dui. Fusce nunc elit, ultricies sed consequat facilisis, ultricies ac risus. Sed mollis dolor vel nulla ullamcorper tincidunt. Donec ligula dolor, varius ac libero et, viverra laoreet justo. Proin eget adipiscing nibh, et consequat arcu.",
  "Maecenas dapibus id risus a dignissim. Aliquam id ligula ligula. Maecenas cursus ornare pretium. Aliquam semper ligula gravida placerat placerat. Vivamus vitae lacinia velit. Sed a odio eu turpis semper vulputate. Fusce vitae augue a dui porta malesuada. Ut imperdiet nulla id turpis rutrum congue vel sed augue. Vivamus id euismod elit. Suspendisse et bibendum nibh. Cras aliquam cursus velit, sit amet mattis turpis accumsan et. Nam vulputate ultricies massa, eget interdum elit viverra eu. Ut in tempor arcu, eu malesuada nunc. Mauris varius quam eget lorem rhoncus pharetra.",
  "Sed pretium sapien arcu, vel pulvinar enim tempor ut. Nam at enim vel est aliquet bibendum. Aliquam ultrices hendrerit dignissim. Morbi nec mattis ipsum, ornare pretium felis. Etiam ac ipsum et urna posuere pharetra. Ut sodales nisi felis. Maecenas eget sem quis nisi lacinia blandit eu vel elit. Etiam nec velit volutpat, lobortis elit ac, suscipit diam. Quisque porta interdum tellus in commodo. Cras porttitor libero in nunc ultrices iaculis. Donec nunc lorem, scelerisque at semper id, ultricies nec lectus.",
  "Nulla non auctor risus. Aliquam erat volutpat. Vivamus convallis velit sed risus sagittis euismod. Praesent volutpat porttitor mattis. Morbi pulvinar turpis ut vehicula iaculis. Donec congue condimentum sapien in rutrum. Vestibulum vitae arcu tellus. Morbi nec volutpat magna. Nam porta vel eros ut rutrum. Pellentesque hendrerit, velit auctor aliquet luctus, augue turpis blandit massa, at tempor sem diam at diam. Donec non elit et velit viverra lobortis. Sed porttitor, magna molestie condimentum rhoncus, libero nunc pellentesque lectus, vel sollicitudin arcu nunc id elit.",
  "Aenean nisl mi, adipiscing vitae sapien vel, consequat molestie mi. Pellentesque diam ipsum, consequat vehicula ante ac, suscipit venenatis tortor. Nunc dictum nisl est, in ullamcorper metus tincidunt sit amet. Donec aliquam erat vel faucibus convallis. Phasellus blandit sem massa, non iaculis quam semper et. Aenean at erat sed mi scelerisque tristique. Nunc vel orci purus."
].each_with_index do |text, index|
  Article.create({
    title: "Mon article #{index+1}",
    body: text
  })
end
